### ISSUE TITLE
Extend form to read form values from input elements.

### ISSUE THREAD

**Issue by alexeiruckiy** [exeto/exeform#121]
You can set form value via `helper.setValue` method, but this approach is separated from original html form interaction with its own values. As a result You have to set default value on form initialization, though it create two sources of truth.

**Comment by exeto** [comment]
The form object doesn't know anything about the original HTML form, so it can be used in React Native.

You should not get values from the original HTML form, use `form.values` instead.

But if you need it, you can do something like this:

```js
import React, { useRef, useEffect } from 'react';
import { FormProvider } from 'exeform';

// This code is not working, it only shows the idea
const Form = ({ form, ...other }) => {
  const ref = useRef();

  useEffect(() => {
    const unsubscribe = form.subscribe(() => {
      setFlattenValuesToForm(ref.current, form.values)
    });

    return unsubscribe;
  }, [form]);

  return (
    <FormProvider value={form}>
      <form {...other} ref={ref} noValidate />
    </FormProvider>
  );
};
```
